### ISSUE TITLE
import AlamofireJsonToObjects not sufficient

### ISSUE THREAD

**Issue by kukudas** [evermeer/AlamofireJsonToObjects#1]
In the readme it is written that the following has to be done to use AlamofireJsonToObjects:

import AlamofireJsonToObjects

If i do this i get the following error: Use of undeclared type 'EVObject'
If i add the following import: import EVReflection it works.

I'm using Cocoapods.

**Comment by evermeer** [comment]
Thanks, you are right, the files that declare the data object classes also need to import EVReflection. I have update the realm for this.
