### ISSUE TITLE
Cannot invoke 'responseObject' 

### ISSUE THREAD

**Issue by podiyaaa** [evermeer/AlamofireJsonToObjects#11]
Hi, im getting this error ..... 
![screen shot 2015-12-28 at 5 15 36 pm](https://cloud.githubusercontent.com/assets/9278751/12018324/3196283a-ad87-11e5-9b62-cb92ba715842.png)

**Comment by evermeer** [comment]
Ah, I see that I did not update the documentation after the previous change of Alamofire. I will do that in a  moment. Instead of returning a response and an error, Alamofire will now return a result. This is now how a cal will look like:

```
            Alamofire.request(.GET, URL)
                .responseObject { (response: Result<Feed, NSError>) in
                if let result = response.value {
                    // Now use your Result
                }
          }

```

**Comment by podiyaaa** [comment]
okay.. i will see and let you know ...  thank you :+1:
