### ISSUE TITLE
Build error happened within carthage

### ISSUE THREAD

**Issue by tk0927** [evermeer/AlamofireJsonToObjects#20]
Thank you for your works,

I tried to get and build your project within carthage, but error happened. 
It seems that  there is no Info.plist in master branch or so. Please fix it.

---

The following build commands failed:
    ProcessInfoPlistFile /Users/XXX/Library/Developer/Xcode/DerivedData/AlamofireJsonToObjects-fjegefcudpictvaahsrfpcutkyjr/Build/Products/Release-iphoneos/AlamofireJsonToObjects.framework/Info.plist AlamofireJsonToObjects/Info.plist
(1 failure)

**Comment by evermeer** [comment]
Cool that you are trying out carthage! I am curious if you are able to do this. 
I fixed the .plist settings for the frameworks. Please let me know if you need anything else.

**Comment by tk0927** [comment]
Thank you for your rapid response!
I tried again, and succeeded to build "AlamofireJsonToObjects.framework".
I’ll try using immediately.

**Comment by tk0927** [comment]
Next error happened during linking to my projects.
Maybe there is no build-settings for my environment.(target platform=iOS)

---

ld: warning: ignoring file /Users/XXX/XXX/Carthage/Build/iOS/AlamofireJsonToObjects.framework/AlamofireJsonToObjects, missing required architecture x86_64 in file /Users/XXX/XXX/Carthage/Build/iOS/AlamofireJsonToObjects.framework/AlamofireJsonToObjects (2 slices)

**Comment by evermeer** [comment]
I'm not sure what I should do to solve that. In the build settings the Architectures are set to standard. and Build active architectures only is set to No. Do you know what else should be done?
http://stackoverflow.com/questions/26552855/xcode-6-1-missing-required-architecture-x86-64-in-file

**Comment by tk0927** [comment]
Sorry, I'm Xcode-beginner, so I don't know what is happening.
I expect the help of someone else.

**Comment by evermeer** [comment]
I will try to create a new project using Carthage myself. I do have to fix another issue first. So it will probably be later this weekend that I will start on this.

**Comment by tk0927** [comment]
Thanks a lot.
I'm looking for fix the problem.

**Comment by eltherion** [comment]
Hi, I have similar issue using your framework with Carthage. Everything builds properly but simulator is not starting. It gives that error: 
"9/1/16 11:20:53.279 PM com.apple.CoreSimulator.CoreSimulatorService[365]: Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=MissingBundleIdentifier, ErrorDescription=Bundle at path /Users/eltherion/Library/Developer/CoreSimulator/Devices/EB070937-C85A-460C-862C-0B64786B9B50/data/Library/Caches/com.apple.mobile.installd.staging/temp.YPr7Uq/extracted/Payload/BODY SCHOOL.app/Frameworks/**AlamofireJsonToObjects.framework did not have a CFBundleIdentifier in its Info.plist**}"

**Comment by evermeer** [comment]
Carthage support is now part of the EVReflection/Alamofire pod. Additional Carthage requirements can be added there.
