### ISSUE TITLE
Swift 3 and Alamofire 4

### ISSUE THREAD

**Issue by Dimillian** [evermeer/AlamofireJsonToObjects#26]
Any ETA on this? I see that the work on EVReflection Swift 3 is almost done too!

**Comment by evermeer** [comment]
Yes, conversion will probably be done later this week.

**Comment by evermeer** [comment]
I finally succeeded in converting to Swift 3. It's currently in a branch called Swift3. I will probably merge to master in a week or 2

**Comment by mdx67** [comment]
Thanks!
