### ISSUE TITLE
compilation errors with Alamofire 2.0.0.beta.1

### ISSUE THREAD

**Issue by jpaas** [evermeer/AlamofireJsonToObjects#3]
In Alamofire 2.0.0.beta.1 the response method signatures have all changed to return a Response instead of a data and error object.

**Comment by evermeer** [comment]
Thanks, I will have a look at it this evening.

**Comment by evermeer** [comment]
After the necessary changes the compiler keeps on crashing with:
Command failed due to signal: Illegal instruction: 4
I will try to fix this tomorrow.

**Comment by evermeer** [comment]
The issue is solved.  The Swift2 branch will now work with Alamofire 2 and Xcode 7 beta 5
