### ISSUE TITLE
Swift 2.3 and Alamofire 3.5 support？

### ISSUE THREAD

**Issue by itamaker** [evermeer/AlamofireJsonToObjects#31]

**Comment by evermeer** [comment]
I was hoping I could skip that one :)
So the you are using Swift 2.3?
I will have a look at it....

**Comment by itamaker** [comment]
yeah,Alamofire 4.0 no supoort iOS8. so.... :)

**Comment by evermeer** [comment]
Now there is a Swift2.3 branch
