### ISSUE TITLE
1.6 version uses EVReflection swift 3 version

### ISSUE THREAD

**Issue by kerem1905** [evermeer/AlamofireJsonToObjects#32]
I am using pod as below:
    pod 'AlamofireJsonToObjects', '~> 1.0'

After running pod update today, I received build errors and noticed EVReflection module changed to swift 3 version like below

open class EVObject: NSObject, NSCoding { // These are redundant in Swift 2+: CustomDebugStringConvertible, CustomStringConvertible, Hashable, Equatable

**Comment by evermeer** [comment]
For now you could force getting the correct branch by also specifying the EVReflection pod version like this:

pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift2.2'

I will try to fix this reference mis match as soon as possible.

**Comment by evermeer** [comment]
The master is now also on Swift3. If you want Swift2.2 then use that specific branch
