### ISSUE TITLE
Use legacy swift error with swift 3

### ISSUE THREAD

**Issue by sagits** [evermeer/AlamofireJsonToObjects#35]
Hi evermeer,

I have just download Xcode 8 (not the beta) and im trying to use the latest version of AlamofireJsonToObjects, but its showing this error:

![image](https://cloud.githubusercontent.com/assets/6174566/19648731/dc333516-99e1-11e6-8b67-c2707758e924.png)

Its just like the alamofire dependency is using an old version of swift. Can you help me please? Thanks in advance.

**Comment by evermeer** [comment]
Did you convert your app to Swift3 and do a clean build?

You could force using the correct version by adding the following lines to your podfile

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by sagits** [comment]
Thanks for answering. Its a new project, the only file it has is the default ViewController created by Xcode. I have tried your approach but received this error:

![image](https://cloud.githubusercontent.com/assets/6174566/19651867/5b68bc6a-99ed-11e6-979c-46d49729a00e.png)

Im new to swift 3, i have just download the new Xcode (as a separate instance because i have old projects). Is there any configuration i need to do to be using swift 3? Can you help me please? Thanks in advance.

**Comment by evermeer** [comment]
Ah, You have got the 3.5 version of Alamofire. You can fix that by setting
`platform :ios, '9.0'`
Alamofire 4.0 which is in Swift 3 has a minimum of 9.0
When you specify a lower version it will fallback to Alamofire 3.5
You could also force getting Alamofire 4.0 by specifying the version in your podfile.
Or if you always want the latest version use:
`pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'`

**Comment by sagits** [comment]
Thanks @evermeer , now it worked.
