### ISSUE TITLE
Swift Compiler Error for Xcode 8.3 

### ISSUE THREAD

**Issue by KarpenkoAV** [evermeer/AlamofireJsonToObjects#42]
Please help to solve the problem
Through a pod installed AlamofireJsonToObjects (2.4.1)
When compiling, I see 2 errors:
AlamofireJsonToObjects.swift: 68: 72: 'NSDictionary' is not convertible to '[AnyHashable: Any]'; Did you mean to use 'as!' To force downcast?
AlamofireJsonToObjects.swift: 130: 98: 'NSDictionary' is not convertible to '[AnyHashable: Any]'; Did you mean to use 'as!' To force downcast?

Xcode Version 8.3 (8E162)

In their Xcode 8.2.1 everything worked fine

**Comment by evermeer** [comment]
could you please switch from AlamofireJsonToObjects to EVReflection/Alamofire

`pod 'EVReflection/Alamofire'`

The functionality is the same. Only EVReflection is maintained actively. EVReflection works on Xcode 8.3
Early next week I have time for updating AlamofireJsonToObjects

**Comment by KarpenkoAV** [comment]
Switching, there are no errors at compilation now.
Thank you for your works!

**Comment by wajahatch888** [comment]
@evermeer , I am using Xcode 8.3.2. I have replaced `pod 'AlamofireJsonToObjects'` with `pod 'EVReflection/Alamofire'` but it is not building anymore. I can separately build Almofire and EvReflection scheme but after removing AlamofireJsonToObjects it is unable to find method.
![screen shot 2017-05-23 at 3 06 07 pm](https://cloud.githubusercontent.com/assets/5916442/26349503/64e2cb0a-3fc9-11e7-9568-81651a815bdf.png)

**Comment by evermeer** [comment]
@wajahatch888 have you also changed your
`import AlamofireJsonToObjects`
to
`import EVReflection`

**Comment by wajahatch888** [comment]
@evermeer , Yes i have done this.

**Comment by evermeer** [comment]
Ah, but you are using Result which is an old Alamofire feature. It has changed to:

            .responseObject { (response: DataResponse<ResponseModel>) in

For details see https://github.com/evermeer/EVReflection/blob/master/UnitTests/AlamofireTests/AlamofireTests.swift

**Comment by wajahatch888** [comment]
Thanks alot 👍
