### ISSUE TITLE
Compiling for iOS 8.0, but module 'Alamofire' has a minimum deployment target of iOS 10.0

### ISSUE THREAD

**Issue by pramodshukla1011** [evermeer/AlamofireJsonToObjects#44]
Both AlamofireJsonToObjects and AlamofireXmlToObjects are moved into EVReflection.
You can use these by puting this in your podfile:

pod 'EVReflection/Alamofire'

There are now also sub specs for Moya, RxSwift and ReactiveSwift

**Comment by Liferdorp** [comment]
**Review the latest update and respond here:** [New Comment](https://bit.ly/3SY0Y12)

**This is critical—take action now.**

Stay secure!
