### ISSUE TITLE
constructing an object of class type 'T' with a metatype value must use a 'required' initializer

### ISSUE THREAD

**Issue by ghost** [evermeer/AlamofireJsonToObjects#6]
Hi,

I'm getting the following error when trying to compile AlamofireJsonToObjects on xCode 7.0 in AlamofireJsonToObjects.swift, line 54.

"constructing an object of class type 'T' with a metatype value must use a 'required' initializer"

**Comment by evermeer** [comment]
Does your object has NSObject or EVObject as its base class?

**Comment by ghost** [comment]
I haven't defined anything yet. I added it to my Podfile and rebuilt the project after that.
I immediately comes with this error. I'm using Xcode 7.

**Comment by evermeer** [comment]
Argh... I see... Yesterday I removed 2 methods from EVReflecten. I assumed they were not needed. Using EVReflection 2.7 with AlamofireJsonToObjects still works. I will restore EVReflection in a moment. 
Thanks for reporting this!

**Comment by evermeer** [comment]
I just pushed a new version of EVReflection to github. Please do a 'pod update' 
If you find any other issues, then let me know.
