### ISSUE TITLE
Using with Swift 2.0 and xcode 7.0

### ISSUE THREAD

**Issue by sagits** [evermeer/AlamofireJsonToObjects#7]
Hi, whats the default version for use with swift 2.0?

I was using:

use_frameworks!
pod "AlamofireJsonToObjects"

to get the latests, but after updating to xcode 7 it's showing a lot of syntax errors. Thanks in advance.

**Comment by sagits** [comment]
My bad, everything working. Closing.

**Comment by evermeer** [comment]
No problem :-) Have fun!
