### ISSUE TITLE
Compilation errors in Xcode 7.0 (7A220)

### ISSUE THREAD

**Issue by Narayane** [evermeer/AlamofireJsonToObjects#8]
Hi,

still the same error when I try to use AlamofireJsonToObjects 1.2.0 with Alamofire 3.0.0-beta.3 (now public enum Result< Value, Error: ErrorType> in Result.swift) from Cocoapods

![alamofire](https://cloud.githubusercontent.com/assets/4921308/10171569/14fd4d22-66db-11e5-94d3-efdfdc5ff2dc.png)

Regards.

**Comment by evermeer** [comment]
The current active release of Alamofire is 2.0.2

When you do a 'pod update' then you should see at least the following 2 passing by:
Using Alamofire (2.0.2)
Using EVReflection (2.9.0)

I see that Alamofire has changed it's method signature again. 
I will create an update as soon as possible...

**Comment by evermeer** [comment]
I just created an 'Alamofire-3' branch for this.
Strange enough it does compile without the errors that you mention.
Lets see if i can find out what went wrong...

**Comment by evermeer** [comment]
Could you please try the Alamofire-3 branch?
When doing a 'pod update' you should see:
Installing Alamofire HEAD based on 3.0.0-beta.3 (was HEAD based on 3.0.0-beta.3)
Using EVReflection (2.9.3)

**Comment by Narayane** [comment]
Hi @evermeer,

not working on my mac.

my podfile:

target 'X' do
    #pod 'Alamofire', '2.0.2'
    #pod 'AlamofireJsonToObjects', '1.2.0'
    pod 'AlamofireJsonToObjects', :git => 'https://github.com/evermeer/AlamofireJsonToObjects.git', :branch => 'Alamofire-3'
end

result:

Analyzing dependencies
Pre-downloading: `AlamofireJsonToObjects` from `https://github.com/evermeer/AlamofireJsonToObjects.git`, branch `Alamofire-3`
Downloading dependencies
Using Alamofire (2.0.2)
Installing AlamofireJsonToObjects 1.2.0 (was 1.2.0)
Installing EVReflection 2.9.3 (was 2.9.1)

Edit : I use cocoapods 0.38.2, pod update --verbose:

Fetching external sources
-> Pre-downloading: `AlamofireJsonToObjects` from `https://github.com/evermeer/AlamofireJsonToObjects.git`, branch `Alamofire-3`

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/evermeer/AlamofireJsonToObjects.git /var/folders/kp/dfj42w7x1xb4cbgq3b0zrj3m0000gq/T/d20151005-1688-1l0otxn
>      --single-branch --depth 1 --branch Alamofire-3
>      Cloning into '/var/folders/kp/dfj42w7x1xb4cbgq3b0zrj3m0000gq/T/d20151005-1688-1l0otxn'...
> Copying AlamofireJsonToObjects from `/Users/s.balard/Library/Caches/CocoaPods/Pods/External/AlamofireJsonToObjects/ebc684575174c1d8af4b65e21c77cd49`
>   to `Pods/AlamofireJsonToObjects`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  M AlamofireJsonToObjects
- Alamofire
- EVReflection

Downloading dependencies
-> Using Alamofire (2.0.2)
-> Installing AlamofireJsonToObjects 1.2.0 (was 1.2.0)
-> Using EVReflection (2.9.3)

Did I forget something or is it just a version label problem?

**Comment by alexcost** [comment]
Hi there,
I am experiencing the same issue as described by Narayane....this is the output of pod update command:

pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `AlamofireJsonToObjects` from `https://github.com/evermeer/AlamofireJsonToObjects.git`, branch `Alamofire-3`
Downloading dependencies
Installing Alamofire 3.0.1 (was 2.0.2)
Installing AlamofireJsonToObjects 1.2.0 (was 1.3.0)
Using BRYXBanner (0.4.1)
Using EVReflection (2.10.0)
Using SwiftyJSON (2.3.0)
Generating Pods project
Integrating client project
Sending stats
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 5 total
pods installed.

Apparently, it is not pointing to the correct version? Thanks a lot in advance

**Comment by alexcost** [comment]
Hi Again,

Issues all go away if the 1.3.0 version is loaded....thanks anyway!

**Comment by evermeer** [comment]
Great to hear that it's solved. 

When you have the following line in your podfile, then you should always have the latest version:
pod "AlamofireJsonToObjects"

Lately Alamofire had quite some breaking changes. I try to make sure that the latest version of AlamofireJsonToObjects keeps working with the latest version of Alamofire. Earlier versions of AlamofireJsonToObjects will only work if you also put Alamofire in jour podfile while specifying the corresponding version
